### ISSUE TITLE
lmao

### ISSUE THREAD

**Issue by cloudcant** [rlarkin212/hentai-cli#1]
bro its cool what you did but how is the world would i install this

**Comment by rlarkin212** [comment]
Hey, 

If you're on mac you can download the bin file here https://github.com/rlarkin212/hentai-cli/releases/tag/v1.1 and place it in `/user/local/bin`.

On window / linux you'll have to compile it yourself, I haven't been able to get a version complied for these targets.

You'll need to `run cargo build --release` (need rust installed) and then grab the file called `target/release/hentai-cli` on linux or `target\release\hentai-cli.exe` on windows.

Then it's just a case of putting the file in `/usr/local/bin` on linux or `Windows\System32` on windows.

You can then call it by using hentai-cli xxxxxx eg.`hentai-cli 177013` and it'll create a folder in the current directory with all the images.

**Comment by c10udz** [comment]
Thx dad
